### ISSUE TITLE
Create folder .vscode

### ISSUE THREAD

**Issue by thepioneer** [earnie123/coffeeshop#3]

**Comment by thepioneer** [comment]
in .vscode generate a file call settings.json

use link below to add your settings.json file code.

https://github.com/PacktPublishing/Angular-6-for-Enterprise-Ready-Web-Applications

**Comment by earnie123** [comment]
edited package.json and tslint.json

**Comment by thepioneer** [comment]
great.  but you forgot install the prettier

npm i -D prettier

this is why its giving me problem.

**Comment by earnie123** [comment]
what is "i" and "-D"?

**Comment by thepioneer** [comment]
I = install
-D = import devDependency and insert package name.

-d = the lower case d = import dependencies

**Comment by earnie123** [comment]
where does it import to ?

**Comment by thepioneer** [comment]
i assume you're stating the -d and -D. It is importing to package.json. Becauise we install a package but if we dont tell it to import the package name into package json dependency or devD... then whoever work on it next would have a hard time understanding what we install.  Package.json file is there to remind us what we install in the node_modules folder.

**Comment by earnie123** [comment]
It worked because we were missing npm i -D prettier.  I failed installation several times due to a space in between  **/* .tw
